# This workflow will send a slack notification every 1st of a month to remind about old branches
name: Clean Old Branches

on:
  workflow_dispatch:
  schedule:
    - cron: '1 * * * *'
jobs:
  list-all-branches:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: list 
        id: list
        run: |
          Output=$(git for-each-ref     refs/heads    --sort=authordate     --format='%(authordate:format:%Y-%m-%d) | %(authordate:relative)  %(align:25,left)%(authorname)%(end) %(refname:strip=3)'    | awk  -v myvar=$(date -j -v-1m +"%Y-%m-%d") '{ if ($1 > myvar) print $0 }'    )
          echo $Output         
          echo "GITHUB_SHA_SHORT=$(echo $Output)" >> $GITHUB_ENV
          
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: 'general'
          # For posting a simple plain text message
          slack-message: "Time to clean some :older_man: branches: \n ${{ env.GITHUB_SHA_SHORT }}"

        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
