name: Octopus Test

on:
  workflow_dispatch:

jobs:
  merge-bug-prs:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
          
      - name: merge
        run: |
          git fetch --all --tags -f
          git checkout -b txn_staging1 origin/master
          Output=$(gh pr list --label bug  --state open | awk  '{print $1}')
          a=($(echo "$Output" | tr ' ' '\n'))
          for i in "${a[@]}"
          do
             echo "merging $i ..."
             gh pr merge $i -s
             # or do whatever with individual element of the array
          done




