name: Octopus Test

on:
  workflow_dispatch:
  pull_request:
    types: [ labeled ]

jobs:
  merge-bug-prs:
    if: ${{ github.event.label.name == 'TEST' }}
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: merge
        run: |
          git fetch --all --tags -f
          git push origin --delete txn_staging1 &>/dev/null
          git checkout -b txn_staging1 origin/main
          Output=$(gh pr list --label TEST  --state open | awk  '{print $1}')
          listToMerge=""
          echo "selected PRs $Output"
          a=($(echo "$Output" | tr ' ' '\n'))
          for i in "${a[@]}"
          do
             echo "checking out PR #$i ..."
             gh pr checkout $i -b  new-pr-$i
             listToMerge="$listToMerge new-pr-$i" 
             # or do whatever with individual element of the array
          done
          git checkout txn_staging1
          git merge $listToMerge
          git push --set-upstream origin txn_staging1
        env:
          GH_TOKEN: ${{ github.token }}



