name: Octopus Test

on:
  workflow_dispatch:

jobs:
  merge-bug-prs:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: merge
        run: |
          git fetch --all --tags -f
          if git show-ref --verify --quiet "refs/heads/txn_staging1"; then
          git push origin --delete txn_staging1
          git checkout -b txn_staging1 origin/main
          Output=$(gh pr list --label TEST  --state open | awk  '{print $1}')
          listToMerge=""
          echo "selected PRs $Output"
          a=($(echo "$Output" | tr ' ' '\n'))
          for i in "${a[@]}"
          do
             echo "checking out PR #$i ..."
             gh pr checkout $i -b  new-pr-$i
             listToMerge="$listToMerge new-pr-$i" 
             # or do whatever with individual element of the array
          done
          git checkout txn_staging1
          git merge $listToMerge
          git push --set-upstream origin txn_staging1
        env:
          GH_TOKEN: ${{ github.token }}

